/*
 * The MIT License
 *
 * Copyright 2024-2025 Μαρέτσικος Χρῆστος.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 *
 * @author Μαρέτσικος Χρῆστος
 */

package PolytLex_plus;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class How_do_we_write extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    
    int numR=127;
    int numG=127;
    int numB=127;
    Color mycolor =  new Color(numR, numG, numB); 
    
    int BG_Color_btnR;
    int BG_Color_btnG;
    int BG_Color_btnB;
    Color BG_Color_btn = new Color (BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
    
    int FG_Color_btnR;
    int FG_Color_btnG;
    int FG_Color_btnB;
    Color FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);
    
    
    int BG_Color_listR;
    int BG_Color_listG;
    int BG_Color_listB;
    Color BG_Color_list=new Color(BG_Color_listR, BG_Color_listG, BG_Color_listB);    
    
    int numSCR;
    int numSCG;
    int numSCB;
    Color mySelColor =  new Color(numSCR, numSCG, numSCB);     
    
    int Yellow_NumR=255, Yellow_NumG=225, Yellow_NumB=100;
    Color mySelected_Color =  new Color(Yellow_NumR, Yellow_NumG, Yellow_NumB);    
    
    Color selectedColor;
    
    String setMyLang="Greek";
    String setMyLangChars="gr" ;
    String pathMyLang="./languages/Greek/how do we write_gr.lang";
    String myForm="/how do we write_";
    
     int setMyTextSize=20;
     String setMyFont="Arial";
     
     
    public How_do_we_write() {
        initComponents();
        JFrame.setDefaultLookAndFeelDecorated(true); //for Title and Icon for Linux
        
        Image small_logo = new ImageIcon(this.getClass().getResource("/PolytLexplus_logo_256x256.png")).getImage();
        this.setIconImage(small_logo);
        
        setDefaultCloseOperation(How_do_we_write.DISPOSE_ON_CLOSE);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_How_do_we_write_ = new javax.swing.JPanel();
        jTextField_FontName_ = new javax.swing.JTextField();
        jTextField_FontSize_ = new javax.swing.JTextField();
        jButton_Big_Letter_ = new javax.swing.JButton();
        jButton_Small_Letter_ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jText_How_do_we_write_ = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextField_FontName_.setEditable(false);
        jTextField_FontName_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_FontName_.setPreferredSize(new java.awt.Dimension(270, 40));

        jTextField_FontSize_.setEditable(false);
        jTextField_FontSize_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_FontSize_.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_FontSize_.setPreferredSize(new java.awt.Dimension(40, 40));

        jButton_Big_Letter_.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton_Big_Letter_.setText("A");
        jButton_Big_Letter_.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton_Big_Letter_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Big_Letter_ActionPerformed(evt);
            }
        });

        jButton_Small_Letter_.setText("A");
        jButton_Small_Letter_.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton_Small_Letter_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Small_Letter_ActionPerformed(evt);
            }
        });

        jText_How_do_we_write_.setEditable(false);
        jScrollPane2.setViewportView(jText_How_do_we_write_);

        javax.swing.GroupLayout jPanel_How_do_we_write_Layout = new javax.swing.GroupLayout(jPanel_How_do_we_write_);
        jPanel_How_do_we_write_.setLayout(jPanel_How_do_we_write_Layout);
        jPanel_How_do_we_write_Layout.setHorizontalGroup(
            jPanel_How_do_we_write_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_How_do_we_write_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_How_do_we_write_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_How_do_we_write_Layout.createSequentialGroup()
                        .addComponent(jTextField_FontName_, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_FontSize_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Big_Letter_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Small_Letter_, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel_How_do_we_write_Layout.setVerticalGroup(
            jPanel_How_do_we_write_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_How_do_we_write_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_How_do_we_write_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_FontName_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_FontSize_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Big_Letter_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Small_Letter_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_How_do_we_write_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_How_do_we_write_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        File fileBG = new File("./settings/colorbg.set");
        File fileBG_btn = new File("./settings/colorbtn.set");
        File fileFG_btn = new File("./settings/colorlttr.set");
        File fileMyFont = new File("./settings/myfont.set");
        File fileMyLang = new File ("./settings/mylang.set");
        File fileMySelColor = new File("./settings/myselcolor.set");
        
        try {
            
            Scanner sML = new Scanner(fileMyLang);
            setMyLang=(sML.nextLine());
            setMyLangChars=(sML.nextLine());
            pathMyLang="./languages/" + setMyLang + myForm + setMyLangChars +".lang";    
            //System.out.println("Γλώσσα: " + setMyLang + " [" + setMyLangChars + "] " + "\n");
            File fileSetMyLang= new File (pathMyLang);
            
            //System.out.println("\n");
            Scanner sBG = new Scanner( fileBG);
            //System.out.println("Χρώμα φόντου");
            numR=(sBG.nextInt());
            //System.out.println(numR);
            numG=(sBG.nextInt());
            //System.out.println(numG);
            numB=(sBG.nextInt());
            //System.out.println(numB);
            //System.out.println("\n");
            mycolor =new Color(numR, numG, numB);
            jPanel_How_do_we_write_.setBackground(mycolor);
            
            Scanner sBG_btn = new Scanner(fileBG_btn);
            //System.out.println("Χρώμα κουμπιών");
            BG_Color_btnR=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnR);
            BG_Color_btnG=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnG);
            BG_Color_btnB=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnB);
            //System.out.println("Χρώμα Λίστας/Πεδίου");
            BG_Color_listR=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listR);
            BG_Color_listG=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listG);
            BG_Color_listB=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listB);
            //System.out.println("");
            //System.out.println("\n");
            BG_Color_btn =new Color(BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
            BG_Color_list=new Color(BG_Color_listR, BG_Color_listG, BG_Color_listB);
            
            Scanner sFG_btn = new Scanner(fileFG_btn);
            //System.out.println("Χρώμα γραμμάτων");
            FG_Color_btnR=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnR);
            FG_Color_btnG=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnG);
            FG_Color_btnB=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnB);
            //System.out.println("\n");
            FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);

            Scanner sMSC = new Scanner( fileMySelColor);
            //System.out.println("Ἐπιλεγμένο χρῶμα");
            numSCR=(sMSC.nextInt());
            //System.out.println(numSCR);
            numSCG=(sMSC.nextInt());
            //System.out.println(numSCG);
            numSCB=(sMSC.nextInt());
            //System.out.println(numSCB);
            //System.out.println("\n");
            mySelColor =new Color(numSCR, numSCG, numSCB);
            selectedColor=mySelColor;
            mySelected_Color=mySelColor;   
            
            jText_How_do_we_write_.setSelectionColor(mySelColor);
            jTextField_FontName_.setSelectionColor(selectedColor);
            jTextField_FontSize_.setSelectionColor(selectedColor);
              
            Scanner sMF = new Scanner(fileMyFont);
            setMyFont=(sMF.nextLine());
            Font myFont = new Font(setMyFont, Font.PLAIN, 20);
            jText_How_do_we_write_.setFont(myFont);
            //System.out.println("Γραμματοσειρά: " + setMyFont + "\n"  + "Μέγεθος: " + setMyTextSize);

            //System.out.println(setMyLang);
            
            if ("Greek".equals(setMyLang)) {
            
            //System.out.println("1");
            
            jText_How_do_we_write_.setContentType("text/html");
            jText_How_do_we_write_.setText("<html><body style=\"background-color:rgb(255,255,235);\"> <H2>Πῶς γράφουμε</H2> <H3>1. Linux</H3>\n" +
"Στὸ λειτουργικὸ σύστημα Linux,\n" +
"θὰ χρειαστεὶ νὰ πατήσουμε ἀπὸ ἕνα ἕως τρία νεκρὰ πλῆκτρα καὶ μετὰ τὸ φωνῆεν, ἐπίσης ἡ διαδικασία θὰ πρέπει νὰ γίνεται μὲ κάποια συγκεκριμένη σειρά. \n" +
"Δίνονται πέντε παραδείγματα: \n" +
"<br>" + 
"<H4><font color=\"green\">ᾄσματα</font></H4> \n" +
"Γιὰ τὸ πρῶτο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο ὑπογεγραμμένη, μετὰ τὸ νεκρὸ πλῆκτρο τόνο, μετὰ τὸ νεκρὸ πλῆκτρο ψιλή, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">α</font></b>. \n" +
"<H4><font color=\"green\">εἶναι</font></H4>\n" +
"Γιὰ τὸ δεύτερο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο περισπωμένη, μετὰ τὸ νεκρὸ πλῆκτρο ψιλή, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">ι</font></b>. \n" +
"<H4><font color=\"green\">συναπτῷ</font></H4>\n" +
"Γιὰ τὸ τελευταῖο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο ὑπογεγραμμένη, μετὰ τὸ νεκρὸ πλῆκτρο περισπωμένη, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">ω</font></b>. \n" +
"<H4><font color=\"green\">λευῗτις</font></H4> \n" +
"Γιὰ τὸ τέταρτο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο περισπωμένη, μετὰ τὸ νεκρὸ πλῆκτρο διαλυτικά, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">ι</font></b>. \n" +
"<H4><font color=\"green\">ᾦσιν</font></H4> \n" +
"Γιὰ τὸ πρῶτο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο ὑπογεγραμμένη, μετὰ τὸ νεκρὸ πλῆκτρο περισπωμένη, μετὰ τὸ νεκρὸ πλῆκτρο ψιλή, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">ω</font></b>. \n" +                    
"<p>" +
"<H3>2. macOS</H3> \n" +
"\n" +
"Στὸ λειτουργικὸ σύστημα macOS, η διαδικασία εἶναι ὅπως καὶ στὸ Linux, μὲ τὴ διαφορὰ ὅτι θὰ χρειαστοῦμε νὰ πατήσουμε ἀπὸ ἕνα ἕως δύο νεκρὰ πλήκτρα καὶ μετὰ τὸ φωνῆεν, καὶ φυσικὰ μὲ κάποια συγκερκριμένη σειρά. \n" +
"Στὰ ἑπόμενα παραδείγματα θὰ χρησιμοποιήσουμε τὶς ἴδιες λέξεις. \n" +
"<br>" + 
"<H4><font color=\"green\">ᾄσματα</font></H4>\n" +
"Γιὰ τὸ πρῶτο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο ποὺ ἔχει τὴ ψιλὴ καὶ τὴν ὀξεῖα, μετὰ τὸ νεκρὸ πλῆκτρο ὑπογεγραμμένη, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">α</font></b>. \n" +
"<H4><font color=\"green\">εἶναι</font></H4> \n" +
"Γιὰ τὸ δεύτερο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο ποὺ ἔχει τὴ ψιλὴ καὶ τὴν περισπωμένη, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">ι</font></b>. \n" +
"<H4><font color=\"green\">συναπτῷ</font></H4> \n" +
"Γιὰ τὸ τελευταῖο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο περισπωμένη, μετὰ τὸ νεκρὸ πλῆκτρο ὑπογεγραμμένη, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">ω</font></b>. \n" +
"<H4><font color=\"green\">λευῗτις</font></H4>\n" +
"Γιὰ τὸ τέταρτο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο ποὺ ἔχει τὴν περισπωμένη, μετὰ τὸ νεκρὸ πλῆκτρο διαλυτικά, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">ι</font></b>. \n" +
"<H4><font color=\"green\">ᾦσιν</font></H4> \n" +
"Γιὰ τὸ πρῶτο γράμμα τῆς λέξης, πρέπει νὰ πατήσουμε τὸ νεκρὸ πλῆκτρο ποὺ ἔχει τὴ ψιλὴ καὶ τὴν περισπωμένη, μετὰ τὸ νεκρὸ πλῆκτρο ὑπογεγραμμένη, καὶ μετὰ πατᾶμε τὸ πλῆκτρο μὲ τὸ φωνῆεν <b><font color=\"red\">ω</font></b>. \n" +                    
"<p>" +
"<H3>3. MS Windows</H3> \n" +
"Στὸ λειτουργικὸ σύστημα MS Windows, ἡ διαδικασία εἴναι πολὺ ἁπλῆ, δηλαδὴ πατᾶμε τὸ νεκρὸ πλῆκτρο μὲ τὸ πνεύμα καὶ τὸν τόνο ποὺ θέλουμε καὶ μετὰ τὸ φωνῆεν. " +

" <p>" +                                
" <p></body></html>");
            jText_How_do_we_write_.setCaretPosition(0);
        
            }
            
            else if (!"Greek".equals(setMyLang)) {
         
            //System.out.println("2");
            
            jText_How_do_we_write_.setContentType("text/html");
            jText_How_do_we_write_.setText("<html><body style=\"background-color:rgb(255,255,235);\"> <H2>How do we write</H2> <H3>1. Linux</H3>\n" +
"In the Linux operating system, we will need to press one to three dead keys and then the vowel, also the process should be done in a certain order.\n" +
"Five examples are given:\n" +
"<br>" + 
"<H4><font color=\"green\">ᾄσματα</font></H4> \n" +
"For the first letter of the word, we need to press the dead key subscript, then the dead key accent, then the dead key smooth, and then we press the key with the vowel <b><font color=\"red\">α</font></b>.\n" +
"<H4><font color=\"green\">εἶναι</font></H4>\n" +
"For the second letter of the word, we have to press the dead key circumflex, then the dead key smooth, and then we press the key with the vowel <b><font color=\"red\">ι</font></b>.\n" +
"<H4><font color=\"green\">συναπτῷ</font></H4>\n" +
"For the last letter of the word, we need to press the dead key subscript, then the dead key circumflex, and then we press the key with the vowel <b><font color=\"red\">ω</font></b>.\n" +
"<H4><font color=\"green\">λευῗτις</font></H4> \n" +
"For the fourth letter of the word, we need to press the dead key circumflex, then the dead key diaeresis, and then we press the key with the vowel <b><font color=\"red\">ι</font></b>. \n" +
"<H4><font color=\"green\">ᾦσιν</font></H4>\n" +
"For the first letter of the word, we need to press the dead key subscript, then the dead key circumflex, then the dead key smooth, and then we press the key with the vowel <b><font color=\"red\">ω</font></b>.\n" +
"<p>" +
"<H3>2. macOS</H3> \n" +
"\n" +
"On the macOS operating system, the process is the same as on Linux, except that we will need to press one to two dead keys, followed by the vowel, and of course in a certain order.\n" +
"In the following examples we will use the same words.\n" +
"<br>" + 
"<H4><font color=\"green\">ᾄσματα</font></H4>\n" +
"For the first letter of the word, we need to press the dead key that has the smooth and the acute, then the dead key subscript, and then we press the key with the vowel <b><font color=\"red\">α</font></b>.\n" +
"<H4><font color=\"green\">εἶναι</font></H4> \n" +
"For the second letter of the word, we have to press the dead key that has the smooth and the circumflex, and then we press the key with the vowel <b><font color=\"red\">ι</font></b>.\n" +
"<H4><font color=\"green\">συναπτῷ</font></H4> \n" +
"For the last letter of the word, we need to press the dead key circumflex, then the dead key subscript, and then we press the key with the vowel <b><font color=\"red\">ω</font></b>.\n" +
"<H4><font color=\"green\">λευῗτις</font></H4>\n" +
"For the fourth letter of the word, we need to press the dead key circumflex, then the dead key diaeresis, and then we press the key with the vowel <b><font color=\"red\">ι</font></b>. \n" +
"<H4><font color=\"green\">ᾦσιν</font></H4>\n" +
"For the first letter of the word, we have to press the dead key that has the smooth and the circumflex, then the dead key subscript, and then we press the key with the vowel <b><font color=\"red\">ω</font></b>.\n" +
"<p>" +
"<H3>3. MS Windows</H3> \n" +
"In the MS Windows operating system, the process is very easy, we just press the dead key with the spirit and the accent we want, and then the vowel." +

" <p>" +                                
"<p></body></html>");
            jText_How_do_we_write_.setCaretPosition(0);
                 
            } 
            
            else {
                
            }
        
            Scanner spathML = new Scanner(fileSetMyLang);
 
            setMyLang=(spathML.nextLine());
            this.setTitle(setMyLang);            
            
            setMyLang=(spathML.nextLine());
            jTextField_FontName_.setToolTipText(setMyLang);

            setMyLang=(spathML.nextLine());
            jTextField_FontSize_.setToolTipText(setMyLang);

            setMyLang=(spathML.nextLine());
            jButton_Big_Letter_.setToolTipText(setMyLang);

            setMyLang=(spathML.nextLine());
            jButton_Small_Letter_.setToolTipText(setMyLang);   
            
        }
            catch (FileNotFoundException ex) {
            }
        
            jTextField_FontName_.setText(setMyFont);
            jTextField_FontName_.setBackground(BG_Color_list);
            jTextField_FontName_.setForeground(FG_Color_btn);
            jTextField_FontSize_.setText("20");
            jTextField_FontSize_.setBackground(BG_Color_list);
            jTextField_FontSize_.setForeground(FG_Color_btn);
            
            jButton_Big_Letter_.setBackground(BG_Color_btn);
            jButton_Small_Letter_.setBackground(BG_Color_btn);
            jButton_Big_Letter_.setForeground(FG_Color_btn);
            jButton_Small_Letter_.setForeground(FG_Color_btn);
   
            
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton_Big_Letter_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Big_Letter_ActionPerformed
        
        if (setMyTextSize<40) {
            setMyTextSize=setMyTextSize+1;

            Font myFontNow = new Font(setMyFont, Font.PLAIN, setMyTextSize);
            jText_How_do_we_write_.setFont(myFontNow);
           
            jTextField_FontName_.setText(setMyFont);
            jTextField_FontSize_.setText(Integer.toString(setMyTextSize));
        }

        else {

        }
        
    }//GEN-LAST:event_jButton_Big_Letter_ActionPerformed

    private void jButton_Small_Letter_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Small_Letter_ActionPerformed

        if (setMyTextSize>10) {
            setMyTextSize=setMyTextSize-1;

            Font myFontNow = new Font(setMyFont, Font.PLAIN, setMyTextSize);
            jText_How_do_we_write_.setFont(myFontNow);
            
            jTextField_FontName_.setText(setMyFont);
            jTextField_FontSize_.setText(Integer.toString(setMyTextSize));
        }

        else {

        }
               
    }//GEN-LAST:event_jButton_Small_Letter_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(How_do_we_write.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(How_do_we_write.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(How_do_we_write.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(How_do_we_write.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new How_do_we_write().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Big_Letter_;
    private javax.swing.JButton jButton_Small_Letter_;
    private javax.swing.JPanel jPanel_How_do_we_write_;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_FontName_;
    private javax.swing.JTextField jTextField_FontSize_;
    private javax.swing.JTextPane jText_How_do_we_write_;
    // End of variables declaration//GEN-END:variables
}
