/*
 * The MIT License
 *
 * Copyright 2024-2025 Μαρέτσικος Χρῆστος.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 *
 * @author Μαρέτσικος Χρῆστος
 */

package PolytLex_plus;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


public class Info extends javax.swing.JFrame {
    
    /**
     * Creates new form Info
     */
    
    int numR=127;
    int numG=127;
    int numB=127;
    Color mycolor =  new Color(numR, numG, numB); 
    
    int BG_Color_btnR;
    int BG_Color_btnG;
    int BG_Color_btnB;
    Color BG_Color_btn = new Color (BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
    
    int FG_Color_btnR;
    int FG_Color_btnG;
    int FG_Color_btnB;
    Color FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);

    String setMyLang="Greek";
    String setMyLangChars="gr" ;
    String pathMyLang="./languages/Greek/info_gr.lang";
    String myForm="/info_";
    
    
    public Info() {
        initComponents();
        JFrame.setDefaultLookAndFeelDecorated(true); //for Title and Icon for Linux
        
        Image small_logo = new ImageIcon(this.getClass().getResource("/PolytLexplus_logo_256x256.png")).getImage();
        this.setIconImage(small_logo);
        
        setDefaultCloseOperation(Info.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Info_ = new javax.swing.JPanel();
        jLabel_PolytLex_ = new javax.swing.JLabel();
        jLabel_Version_ = new javax.swing.JLabel();
        jLabel_Creator_ = new javax.swing.JLabel();
        jButton_Licence_ = new javax.swing.JButton();
        jButton_Close_ = new javax.swing.JButton();
        jLabel_Copyright_ = new javax.swing.JLabel();
        jLabel_VersionNumber_ = new javax.swing.JLabel();
        jLabel_Program_Name_ = new javax.swing.JLabel();
        jLabel_email_1_ = new javax.swing.JLabel();
        jLabel_email_2_ = new javax.swing.JLabel();
        jLabel1_logo = new javax.swing.JLabel();
        jLabel2_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Σχετικὰ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_Info_.setPreferredSize(new java.awt.Dimension(380, 489));

        jLabel_PolytLex_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_PolytLex_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_PolytLex_.setText("PolytLex+");
        jLabel_PolytLex_.setPreferredSize(new java.awt.Dimension(350, 20));

        jLabel_Version_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Version_.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Version_.setText(" Ἔκδοση:");
        jLabel_Version_.setPreferredSize(new java.awt.Dimension(170, 20));

        jLabel_Creator_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Creator_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Creator_.setText("Δημιουργός: Μαρέτσικος Χρῆστος");
        jLabel_Creator_.setPreferredSize(new java.awt.Dimension(350, 20));

        jButton_Licence_.setBackground(new java.awt.Color(242, 242, 242));
        jButton_Licence_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Licence_.setText("Ἄδεια χρήσης");
        jButton_Licence_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Licence_ActionPerformed(evt);
            }
        });

        jButton_Close_.setBackground(new java.awt.Color(242, 242, 242));
        jButton_Close_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Close_.setText("Κλείσιμο");
        jButton_Close_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Close_ActionPerformed(evt);
            }
        });

        jLabel_Copyright_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Copyright_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Copyright_.setText("Πνευματικὰ δικαιώματα © 2024 - 2025");
        jLabel_Copyright_.setPreferredSize(new java.awt.Dimension(350, 20));

        jLabel_VersionNumber_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_VersionNumber_.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_VersionNumber_.setText("1.1.7.2 (64-bit)");
        jLabel_VersionNumber_.setPreferredSize(new java.awt.Dimension(174, 20));

        jLabel_Program_Name_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Program_Name_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Program_Name_.setText("Ἑλληνικὸ Πολυτονικὸ Λεξικό");
        jLabel_Program_Name_.setPreferredSize(new java.awt.Dimension(350, 20));

        jLabel_email_1_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_email_1_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_email_1_.setText("e-mail: chrisgrelec@sch.gr");
        jLabel_email_1_.setPreferredSize(new java.awt.Dimension(350, 20));

        jLabel_email_2_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_email_2_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_email_2_.setText("e-mail: newcosmos88@yahoo.gr");
        jLabel_email_2_.setPreferredSize(new java.awt.Dimension(350, 20));

        jLabel1_logo.setFont(new java.awt.Font("Times New Roman", 0, 100)); // NOI18N
        jLabel1_logo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1_logo.setText("ᾄ");

        jLabel2_logo.setFont(new java.awt.Font("Times New Roman", 1, 70)); // NOI18N
        jLabel2_logo.setText("+");

        javax.swing.GroupLayout jPanel_Info_Layout = new javax.swing.GroupLayout(jPanel_Info_);
        jPanel_Info_.setLayout(jPanel_Info_Layout);
        jPanel_Info_Layout.setHorizontalGroup(
            jPanel_Info_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Info_Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_Info_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_Program_Name_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_Info_Layout.createSequentialGroup()
                        .addComponent(jLabel_Version_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_VersionNumber_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Copyright_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Info_Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton_Licence_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Close_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addComponent(jLabel_email_1_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_email_2_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_Info_Layout.createSequentialGroup()
                        .addComponent(jLabel1_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_PolytLex_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Creator_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel_Info_Layout.setVerticalGroup(
            jPanel_Info_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Info_Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_Info_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_PolytLex_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Program_Name_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Info_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Version_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VersionNumber_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Creator_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Copyright_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_email_1_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_email_2_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel_Info_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Licence_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Close_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Info_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Info_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        File fileBG = new File("./settings/colorbg.set");
        File fileBG_btn = new File("./settings/colorbtn.set");
        File fileFG_btn = new File("./settings/colorlttr.set");
        File fileMyLang = new File ("./settings/mylang.set");
        
        try {
            
            Scanner sML = new Scanner(fileMyLang);
            setMyLang=(sML.nextLine());
            setMyLangChars=(sML.nextLine());
            pathMyLang="./languages/" + setMyLang + myForm + setMyLangChars +".lang";    
            //System.out.println("Γλώσσα: " + setMyLang + " [" + setMyLangChars + "] " + "\n");
            File fileSetMyLang= new File (pathMyLang);
             
            //System.out.println("\n");
            Scanner sBG = new Scanner( fileBG);
            //System.out.println("Χρώμα φόντου");
            numR=(sBG.nextInt());
            //System.out.println(numR);
            numG=(sBG.nextInt());
            //System.out.println(numG);
            numB=(sBG.nextInt());
            //System.out.println(numB);
            //System.out.println("\n");
            mycolor =new Color(numR, numG, numB);
            jPanel_Info_.setBackground(mycolor);
            
            Scanner sBG_btn = new Scanner(fileBG_btn);
            //System.out.println("Χρώμα κουμπιών");
            BG_Color_btnR=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnR);
            BG_Color_btnG=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnG);
            BG_Color_btnB=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnB);
            //System.out.println("\n");
            BG_Color_btn =new Color(BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
            
            Scanner sFG_btn = new Scanner(fileFG_btn);
            //System.out.println("Χρώμα γραμμάτων");
            FG_Color_btnR=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnR);
            FG_Color_btnG=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnG);
            FG_Color_btnB=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnB);
            //System.out.println("\n");
            FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);
        
            jLabel_PolytLex_.setForeground(FG_Color_btn);
            jLabel1_logo.setForeground(FG_Color_btn);
            jLabel2_logo.setForeground(FG_Color_btn);
            jLabel_Program_Name_.setForeground(FG_Color_btn);
            jLabel_Version_.setForeground(FG_Color_btn);
            jLabel_VersionNumber_.setForeground(FG_Color_btn);
            jLabel_Creator_.setForeground(FG_Color_btn);
            jLabel_Copyright_.setForeground(FG_Color_btn);
            jLabel_email_1_.setForeground(FG_Color_btn);
            jLabel_email_2_.setForeground(FG_Color_btn);

            jButton_Licence_.setBackground(BG_Color_btn);
            jButton_Licence_.setForeground(FG_Color_btn);            
            jButton_Close_.setBackground(BG_Color_btn);
            jButton_Close_.setForeground(FG_Color_btn);
            
            
            Scanner spathML = new Scanner(fileSetMyLang);
            
            setMyLang=(spathML.nextLine());
            this.setTitle(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jLabel_Program_Name_.setText(setMyLang);
                    
            setMyLang=(spathML.nextLine());
            jLabel_Version_.setText(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jLabel_Creator_.setText(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jLabel_Copyright_.setText(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jButton_Licence_.setText(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jButton_Close_.setText(setMyLang);
            
                        
            }
        
        catch (FileNotFoundException ex) {
           
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton_Close_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Close_ActionPerformed

        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object

    }//GEN-LAST:event_jButton_Close_ActionPerformed

    private void jButton_Licence_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Licence_ActionPerformed

        Licence JFrameLicence = new Licence();
        JFrameLicence.show();
    }//GEN-LAST:event_jButton_Licence_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Close_;
    private javax.swing.JButton jButton_Licence_;
    private javax.swing.JLabel jLabel1_logo;
    private javax.swing.JLabel jLabel2_logo;
    private javax.swing.JLabel jLabel_Copyright_;
    private javax.swing.JLabel jLabel_Creator_;
    private javax.swing.JLabel jLabel_PolytLex_;
    private javax.swing.JLabel jLabel_Program_Name_;
    private javax.swing.JLabel jLabel_VersionNumber_;
    private javax.swing.JLabel jLabel_Version_;
    private javax.swing.JLabel jLabel_email_1_;
    private javax.swing.JLabel jLabel_email_2_;
    private javax.swing.JPanel jPanel_Info_;
    // End of variables declaration//GEN-END:variables
}
