/*
 * The MIT License
 *
 * Copyright 2024-2025 Μαρέτσικος Χρῆστος.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 *
 * @author Μαρέτσικος Χρῆστος
 */

package PolytLex_plus;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


public class Licence extends javax.swing.JFrame {
        
    /**
     * Creates new form Licence
     */
        
    int numR=127;
    int numG=127;
    int numB=127;
    Color mycolor =  new Color(numR, numG, numB); 
    
    int BG_Color_btnR;
    int BG_Color_btnG;
    int BG_Color_btnB;
    Color BG_Color_btn = new Color (BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
    
    int FG_Color_btnR;
    int FG_Color_btnG;
    int FG_Color_btnB;
    Color FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);
    
    int numSCR;
    int numSCG;
    int numSCB;
    Color mySelColor =  new Color(numSCR, numSCG, numSCB); 
    Color selectedColor;
    
    int myYellow_NumR=255, myYellow_NumG=225, myYellow_NumB=100;
    Color mySelected_Color =  new Color(myYellow_NumR, myYellow_NumG, myYellow_NumB);    
    
    String setMyLang="Greek";
    String setMyLangChars="gr" ;
    String pathMyLang="./languages/Greek/licence_gr.lang";
    String myForm="/licence_";

     int setMyTextSize=17;
     String setMyFont="Arial";    
    
    public Licence() {
        initComponents();
        JFrame.setDefaultLookAndFeelDecorated(true); //for Title and Icon for Linux
        
        Image small_logo = new ImageIcon(this.getClass().getResource("/PolytLexplus_logo_256x256.png")).getImage();
        this.setIconImage(small_logo);
        
        setDefaultCloseOperation(Licence.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Licence_ = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jText_Licence_MIT_ = new javax.swing.JTextPane();
        jButton_Close_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ἄδεια χρήσης");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_Licence_.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_Licence_.setPreferredSize(new java.awt.Dimension(694, 655));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(654, 480));

        jText_Licence_MIT_.setEditable(false);
        jText_Licence_MIT_.setBackground(new java.awt.Color(242, 242, 242));
        jText_Licence_MIT_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jText_Licence_MIT_);

        jButton_Close_.setBackground(new java.awt.Color(242, 242, 242));
        jButton_Close_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Close_.setText("Κλείσιμο");
        jButton_Close_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Close_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Licence_Layout = new javax.swing.GroupLayout(jPanel_Licence_);
        jPanel_Licence_.setLayout(jPanel_Licence_Layout);
        jPanel_Licence_Layout.setHorizontalGroup(
            jPanel_Licence_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Licence_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_Licence_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Close_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel_Licence_Layout.setVerticalGroup(
            jPanel_Licence_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Licence_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Close_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Licence_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Licence_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        File fileBG = new File("./settings/colorbg.set");
        File fileBG_btn = new File("./settings/colorbtn.set");
        File fileFG_btn = new File("./settings/colorlttr.set");
        File fileMyFont = new File("./settings/myfont.set");        
        File fileMyLang = new File ("./settings/mylang.set");
        File fileMySelColor = new File("./settings/myselcolor.set");        
        
        try {
            
            Scanner sML = new Scanner(fileMyLang);
            setMyLang=(sML.nextLine());
            setMyLangChars=(sML.nextLine());
            pathMyLang="./languages/" + setMyLang + myForm + setMyLangChars +".lang";    
            //System.out.println("Γλώσσα: " + setMyLang + " [" + setMyLangChars + "] " + "\n");
            File fileSetMyLang= new File (pathMyLang);
            
            //System.out.println("\n");
            Scanner sBG = new Scanner( fileBG);
            //System.out.println("Χρώμα φόντου");
            numR=(sBG.nextInt());
            //System.out.println(numR);
            numG=(sBG.nextInt());
            //System.out.println(numG);
            numB=(sBG.nextInt());
            //System.out.println(numB);
            //System.out.println("\n");
            mycolor =new Color(numR, numG, numB);
            jPanel_Licence_.setBackground(mycolor);
            
            Scanner sBG_btn = new Scanner(fileBG_btn);
            //System.out.println("Χρώμα κουμπιών");
            BG_Color_btnR=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnR);
            BG_Color_btnG=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnG);
            BG_Color_btnB=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnB);
            //System.out.println("\n");
            BG_Color_btn =new Color(BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
            
            Scanner sFG_btn = new Scanner(fileFG_btn);
            //System.out.println("Χρώμα γραμμάτων");
            FG_Color_btnR=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnR);
            FG_Color_btnG=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnG);
            FG_Color_btnB=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnB);
            //System.out.println("\n");
            FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);
            
            jButton_Close_.setBackground(BG_Color_btn);
            jButton_Close_.setForeground(FG_Color_btn);
            
            Scanner sMSC = new Scanner( fileMySelColor);
            //System.out.println("Ἐπιλεγμένο χρῶμα");
            numSCR=(sMSC.nextInt());
            //System.out.println(numSCR);
            numSCG=(sMSC.nextInt());
            //System.out.println(numSCG);
            numSCB=(sMSC.nextInt());
            //System.out.println(numSCB);
            //System.out.println("\n");
            mySelColor =new Color(numSCR, numSCG, numSCB);
            selectedColor=mySelColor;
            mySelected_Color=mySelColor;  
            jText_Licence_MIT_.setSelectionColor(selectedColor);
            
            Scanner sMF = new Scanner(fileMyFont);
            setMyFont=(sMF.nextLine());
            Font myFont = new Font(setMyFont, Font.PLAIN, 17);
            jText_Licence_MIT_.setFont(myFont);
            //System.out.println("Γραμματοσειρά: " + setMyFont + "\n"  + "Μέγεθος: " + setMyTextSize);            

        
            //System.out.println(setMyLang);
            
            if ("Greek".equals(setMyLang)) {
            
            //System.out.println("1");
            
            jText_Licence_MIT_.setContentType("text/html");
            jText_Licence_MIT_.setText("<html><body style=\"background-color:rgb(255,255,235);\"> <H2>Ἡ ἄδεια MIT</H2> <H3>Πνευματικὰ δικαιώματα © 2024 - 2025 Μαρέτσικος Χρῆστος</H3>\n" +
" Μὲ τὸ παρὸν χορηγεῖται δωρεὰν ἄδεια σὲ κάθε πρόσωπο ποὺ ἀποκτᾶ ἀντίγραφο" +
" αὐτοῦ τοῦ λογισμικοῦ καὶ τῶν σχετικῶν ἀρχείων τεκμηρίωσης (τὸ \"Λογισμικό\"), νὰ ἐμπορεύεται" +
" τὸ Λογισμικὸ χωρὶς περιορισμούς, συμπεριλαμβανομένων, χωρὶς περιορισμό, τῶν δικαιωμάτων" +
" χρήσης, ἀντιγραφῆς, τροποποίησης, συγχώνευσης, δημοσίευσης, διανομῆς, ὑποαδειοδότησης ἤ/καὶ πώλησης" +
"  ἀντιγράφων τοῦ Λογισμικοῦ, καὶ νὰ ἐπιτρέπει στὰ πρόσωπα στὰ ὁποῖα παρέχεται τὸ Λογισμικὸ νὰ τὸ κάνουν," +
"  ὑπὸ τὶς ἀκόλουθες προϋποθέσεις:" +
" <p>" +                
" Ἡ παραπάνω εἰδοποίηση περὶ πνευματικῶν δικαιωμάτων καὶ ἡ παροῦσα εἰδοποίηση περὶ ἄδειας θὰ πρέπει" +
" νὰ περιλαμβάνονται σὲ ὅλα τὰ ἀντίγραφα ἢ τὰ οὐσιώδη τμήματα τοῦ Λογισμικοῦ." +
" <p>" +                                
" ΤΟ ΛΟΓΙΣΜΙΚΟ ΠΑΡΕΧΕΤΑΙ «ΩΣ ΕΧΕΙ», ΧΩΡΙΣ ΚΑΜΙΑ ΕΓΓΥΗΣΗ ΟΠΟΙΟΥΔΗΠΟΤΕ ΕΙΔΟΥΣ, ΡΗΤΗ Ἤ ΣΙΩΠΗΡΗ," +
" ΣΥΜΠΕΡΙΛΑΜΒΑΝΟΜΕΝΩΝ, ΕΝΔΕΙΚΤΙΚΑ, ΤΩΝ ΕΓΓΥΗΣΕΩΝ ΕΜΠΟΡΕΥΣΙΜΟΤΗΤΑΣ, ΚΑΤΑΛΛΗΛΟΤΗΤΑΣ" +
" ΓΙΑ ΣΥΓΚΕΚΡΙΜΕΝΟ ΣΚΟΠΟ ΚΑΙ ΜΗ ΠΑΡΑΒΙΑΣΗΣ. ΣΕ ΚΑΜΙΑ ΠΕΡΙΠΤΩΣΗ ΟΙ ΣΥΓΓΡΑΦΕΙΣ Ἤ ΟΙ ΚΑΤΟΧΟΙ" +
" ΤΩΝ ΠΝΕΥΜΑΤΙΚΩΝ ΔΙΚΑΙΩΜΑΤΩΝ ΔΕΝ ΕΥΘΥΝΟΝΤΑΙ ΓΙΑ ΟΠΟΙΑΔΗΠΟΤΕ ΑΞΙΩΣΗ, ΖΗΜΙΑ Ἤ ΑΛΛΗ ΕΥΘΥΝΗ," +
" ΕΙΤΕ ΜΕ ΑΓΩΓΗ ΣΥΜΒΟΛΑΙΟΥ, ΑΔΙΚΟΠΡΑΞΙΑΣ ΕΙΤΕ ΜΕ ΑΛΛΟ ΤΡΟΠΟ, ΠΟΥ ΠΡΟΚΥΠΤΕΙ" +
" ΑΠΟ Ἤ ΣΕ ΣΧΕΣΗ ΜΕ ΤΟ ΛΟΓΙΣΜΙΚΟ Ἤ ΤΗ ΧΡΗΣΗ Ἤ ΑΛΛΕΣ ΣΥΝΑΛΛΑΓΕΣ ΜΕ ΤΟ ΛΟΓΙΣΜΙΚΟ." +
" <p>" +                
" Θὰ πρέπει νὰ ἔχετε λάβει ἕνα ἀντίγραφο τῆς Ἄδειας MIT μαζὶ μὲ αὐτὸ τὸ πρόγραμμα." +
" <p>" +  
" Ἂν ὄχι, δεῖτε στὸ σύνδεσμο https://opensource.org/license/MIT" +
" <p>" +                                
" <p></body></html>");
            jText_Licence_MIT_.setCaretPosition(0);
        
            }
            
            if (!"Greek".equals(setMyLang)) {
         
            //System.out.println("2");
            
            jText_Licence_MIT_.setContentType("text/html");
            jText_Licence_MIT_.setText("<html><body style=\"background-color:rgb(255,255,235);\"> <H2>The MIT License</H2> <H3>Copyright © 2024 - 2025 Maretsikos Christos</H3>\n" +
" Permission is hereby granted, free of charge, to any person obtaining a copy" +
" of this software and associated documentation files (the \"Software\"), to deal" +
" in the Software without restriction, including without limitation the rights" +
" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell" +
" copies of the Software, and to permit persons to whom the Software is" +
" furnished to do so, subject to the following conditions:" +
" <p>" +                
" The above copyright notice and this permission notice shall be included in" +
" all copies or substantial portions of the Software." +
" <p>" +                                
" THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR" +
" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY," +
" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE" +
" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER" +
" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM," +
" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN" +
" THE SOFTWARE." +
" <p>" +                
" You should have received a copy of the MIT License with this program." +
" <p>" +  
" If not, see the link https://opensource.org/license/MIT" +
" <p>" +                                
"<p></body></html>");
            jText_Licence_MIT_.setCaretPosition(0);
                 
            }    
        
            Scanner spathML = new Scanner(fileSetMyLang);

            setMyLang=(spathML.nextLine());
            this.setTitle(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jButton_Close_.setText(setMyLang);
        
        
            }
            catch (FileNotFoundException ex) {
            }
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton_Close_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Close_ActionPerformed
        
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
        
    }//GEN-LAST:event_jButton_Close_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Licence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Licence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Licence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Licence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Licence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Close_;
    private javax.swing.JPanel jPanel_Licence_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jText_Licence_MIT_;
    // End of variables declaration//GEN-END:variables
}
