/*
 * The MIT License
 *
 * Copyright 2024-2025 Μαρέτσικος Χρῆστος.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 *
 * @author Μαρέτσικος Χρῆστος
 */

package PolytLex_plus;

import static PolytLex_plus.PolytLex_plus.Editor_or_VirtualKeyboard;
import static PolytLex_plus.PolytLex_plus.flag_insertOpenFileDialog;
import static PolytLex_plus.PolytLex_plus.setCurrentFile;
import static PolytLex_plus.PolytLex_plus.flag_Question;
import static PolytLex_plus.PolytLex_plus.questionLabel;
import static PolytLex_plus.PolytLex_plus.sendmeTheFileName;
import static PolytLex_plus.PolytLex_plus.myFileName;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Question_for_Save_File extends javax.swing.JDialog {

    /**
     * Creates new form Question_for_Save
     */
    
    int myNum_Save=0;

    int numR=127;
    int numG=127;
    int numB=127;
    Color mycolor =  new Color(numR, numG, numB); 
    
    int BG_Color_btnR;
    int BG_Color_btnG;
    int BG_Color_btnB;
    Color BG_Color_btn = new Color (BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
    
    int FG_Color_btnR;
    int FG_Color_btnG;
    int FG_Color_btnB;
    Color FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);
    
    int BG_Color_listR;
    int BG_Color_listG;
    int BG_Color_listB;
    Color BG_Color_list = new Color (BG_Color_listR, BG_Color_listG, BG_Color_listB);
    
    private File myCurrentFile; 
    
    String setMyLang="Greek";
    String setMyLangChars="gr" ;
    String pathMyLang="./languages/Greek/question for save_gr.lang";
    String myForm="/question for save_";
    
    public Question_for_Save_File(java.awt.Frame myDialog_SAVE, boolean modal) {
        
        super(myDialog_SAVE, modal);
        initComponents();
        
        
        JFrame.setDefaultLookAndFeelDecorated(true); //for Title and Icon for Linux
        
        Image small_logo = new ImageIcon(this.getClass().getResource("/PolytLexplus_logo_256x256.png")).getImage();
        this.setIconImage(small_logo);
        
        
        jPanel_Question_for_Save_.setBackground(mycolor);
        setDefaultCloseOperation(Question_for_Save_File.DISPOSE_ON_CLOSE);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Question_for_Save_ = new javax.swing.JPanel();
        jLabel_QuestionSave_ = new javax.swing.JLabel();
        jButton_Save_ = new javax.swing.JButton();
        jButton_NoSave_ = new javax.swing.JButton();
        jButton_Cancel_ = new javax.swing.JButton();
        jLabel_Document_Name_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel_QuestionSave_.setBackground(new java.awt.Color(153, 255, 51));
        jLabel_QuestionSave_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_QuestionSave_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_QuestionSave_.setText("Θέλετε νὰ ἀποθηκευτοῦν οἱ ἀλλαγὲς στὸ ἔγγραφο;");
        jLabel_QuestionSave_.setPreferredSize(new java.awt.Dimension(470, 20));

        jButton_Save_.setBackground(new java.awt.Color(242, 242, 242));
        jButton_Save_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Save_.setText("Ναὶ");
        jButton_Save_.setPreferredSize(new java.awt.Dimension(140, 35));
        jButton_Save_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Save_ActionPerformed(evt);
            }
        });

        jButton_NoSave_.setBackground(new java.awt.Color(242, 242, 242));
        jButton_NoSave_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_NoSave_.setText("Ὄχι");
        jButton_NoSave_.setPreferredSize(new java.awt.Dimension(140, 35));
        jButton_NoSave_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NoSave_ActionPerformed(evt);
            }
        });

        jButton_Cancel_.setBackground(new java.awt.Color(242, 242, 242));
        jButton_Cancel_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Cancel_.setText("Ἄκυρο");
        jButton_Cancel_.setPreferredSize(new java.awt.Dimension(140, 35));
        jButton_Cancel_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cancel_ActionPerformed(evt);
            }
        });

        jLabel_Document_Name_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Document_Name_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Document_Name_.setPreferredSize(new java.awt.Dimension(470, 20));

        javax.swing.GroupLayout jPanel_Question_for_Save_Layout = new javax.swing.GroupLayout(jPanel_Question_for_Save_);
        jPanel_Question_for_Save_.setLayout(jPanel_Question_for_Save_Layout);
        jPanel_Question_for_Save_Layout.setHorizontalGroup(
            jPanel_Question_for_Save_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Question_for_Save_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_Question_for_Save_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_QuestionSave_, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Question_for_Save_Layout.createSequentialGroup()
                        .addComponent(jButton_Save_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton_NoSave_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton_Cancel_, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Document_Name_, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel_Question_for_Save_Layout.setVerticalGroup(
            jPanel_Question_for_Save_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Question_for_Save_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_QuestionSave_, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Document_Name_, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Question_for_Save_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Save_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_NoSave_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Cancel_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Question_for_Save_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Question_for_Save_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        setTitle("Εἰκονικὸ πληκτρολόγιο");
         
        File fileBG = new File("./settings/colorbg.set");
        File fileBG_btn = new File("./settings/colorbtn.set");
        File fileFG_btn = new File("./settings/colorlttr.set");
        File fileMyLang = new File ("./settings/mylang.set");
        
        try {
            
            Scanner sML = new Scanner(fileMyLang);
            setMyLang=(sML.nextLine());
            setMyLangChars=(sML.nextLine());
            pathMyLang="./languages/" + setMyLang + myForm + setMyLangChars +".lang";    
            //System.out.println("Γλώσσα: " + setMyLang + " [" + setMyLangChars + "] " + "\n");
            File fileSetMyLang= new File (pathMyLang);
            
            //System.out.println("\n");
            Scanner sBG = new Scanner( fileBG);
            //System.out.println("Χρώμα φόντου");
            numR=(sBG.nextInt());
            //System.out.println(numR);
            numG=(sBG.nextInt());
            //System.out.println(numG);
            numB=(sBG.nextInt());
            //System.out.println(numB);
            //System.out.println("\n");
            mycolor =new Color(numR, numG, numB);
            jPanel_Question_for_Save_.setBackground(mycolor);
            
            Scanner sBG_btn = new Scanner(fileBG_btn);
            //System.out.println("Χρώμα κουμπιών");
            BG_Color_btnR=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnR);
            BG_Color_btnG=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnG);
            BG_Color_btnB=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnB);
            //System.out.println("Χρώμα Λίστας/Πεδίου");
            BG_Color_listR=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listR);
            BG_Color_listG=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listG);
            BG_Color_listB=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listB);
            //System.out.println("");
            //System.out.println("\n");
            BG_Color_btn = new Color(BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
            BG_Color_list= new Color(BG_Color_listR, BG_Color_listG, BG_Color_listB);
            
            Scanner sFG_btn = new Scanner(fileFG_btn);
            //System.out.println("Χρώμα γραμμάτων");
            FG_Color_btnR=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnR);
            FG_Color_btnG=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnG);
            FG_Color_btnB=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnB);
            //System.out.println("\n");
            FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);
            jPanel_Question_for_Save_.setForeground(FG_Color_btn);
            
            jLabel_QuestionSave_.setBackground(BG_Color_btn);
            jLabel_QuestionSave_.setForeground(FG_Color_btn);
            jLabel_Document_Name_.setBackground(BG_Color_btn);
            jLabel_Document_Name_.setForeground(FG_Color_btn);
            
            if (flag_insertOpenFileDialog==true){
                jLabel_Document_Name_.setText(myFileName);
                setCurrentFile=myFileName;
                sendmeTheFileName=myFileName;
                flag_insertOpenFileDialog=false;
                //System.out.println("flag_insertOpenFileDialog was true");
            }
            else{
                jLabel_Document_Name_.setText(myFileName);
                //System.out.println("flag_insertOpenFileDialog was false");
            }
            
            flag_Question=true;
            questionLabel=jLabel_Document_Name_.getText();
            jButton_Save_.setBackground(BG_Color_btn);
            jButton_Save_.setForeground(FG_Color_btn);
            jButton_NoSave_.setBackground(BG_Color_btn);
            jButton_NoSave_.setForeground(FG_Color_btn);
            jButton_Cancel_.setBackground(BG_Color_btn);
            jButton_Cancel_.setForeground(FG_Color_btn);
            
            Scanner spathML = new Scanner(fileSetMyLang);
            
            setMyLang=(spathML.nextLine());
            this.setTitle(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jLabel_QuestionSave_.setText(setMyLang);
                    
            setMyLang=(spathML.nextLine());
            jButton_Save_.setText(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jButton_NoSave_.setText(setMyLang);
            
            setMyLang=(spathML.nextLine());
            jButton_Cancel_.setText(setMyLang);            
      
        }    
           catch (FileNotFoundException ex) {
           
        }        
       
    }//GEN-LAST:event_formWindowOpened

    private void jButton_Save_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Save_ActionPerformed
        
        //System.out.println("A");
        setVisible(false);
        dispose();
        
        Save_File_Dialog myDialog_Save = new Save_File_Dialog(this, true);
        myDialog_Save.setVisible(true);  
        
       
        //System.out.println("sendmeTheFileName: " + sendmeTheFileName );

        
        myNum_Save=1;
        
        if (Editor_or_VirtualKeyboard==true) {
            Virtual_Keyboard.check_VK_or_ED=myNum_Save;
        }
        else {
            Editor.check_VK_or_ED=myNum_Save;
        }            
        
        
        setCurrentFile="";
        setCurrentFile=jLabel_Document_Name_.toString();
        setVisible(false);
        dispose();
    
 
    }//GEN-LAST:event_jButton_Save_ActionPerformed

    private void jButton_NoSave_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NoSave_ActionPerformed
               
        myNum_Save=1;
        
        if (Editor_or_VirtualKeyboard==true) {
            Virtual_Keyboard.check_VK_or_ED=myNum_Save;
        }
        else {
            Editor.check_VK_or_ED=myNum_Save;
        } 

        setCurrentFile=jLabel_Document_Name_.toString();
        setVisible(false);
        dispose();
 
                
    }//GEN-LAST:event_jButton_NoSave_ActionPerformed

    private void jButton_Cancel_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cancel_ActionPerformed
      
        setVisible(false);
        dispose();
            
    }//GEN-LAST:event_jButton_Cancel_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question_for_Save_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question_for_Save_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question_for_Save_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question_for_Save_File.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Question_for_Save_File mydialog = new Question_for_Save_File (new javax.swing.JFrame(), true);
                mydialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                        
                    }
                });
                mydialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel_;
    private javax.swing.JButton jButton_NoSave_;
    private javax.swing.JButton jButton_Save_;
    private javax.swing.JLabel jLabel_Document_Name_;
    private javax.swing.JLabel jLabel_QuestionSave_;
    private javax.swing.JPanel jPanel_Question_for_Save_;
    // End of variables declaration//GEN-END:variables
}
