/*
 * The MIT License
 *
 * Copyright 2024-2025 Μαρέτσικος Χρῆστος.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 *
 * @author Μαρέτσικος Χρῆστος
 */

package PolytLex_plus;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class Saving_Theme extends javax.swing.JFrame {
    
    /**
     * Creates new form Saving_Theme
     */
      
    String pathThemes=("./themes/");
    String myFilename;
    
    int numR=127;
    int numG=127;
    int numB=127;
    Color mycolor =  new Color(numR, numG, numB); 
    
    int BG_Color_btnR;
    int BG_Color_btnG;
    int BG_Color_btnB;
    Color BG_Color_btn = new Color (BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
    
    int BG_Color_listR;
    int BG_Color_listG;
    int BG_Color_listB;
    Color BG_Color_list = new Color (BG_Color_listR, BG_Color_listG, BG_Color_listB);
     
    int FG_Color_btnR;
    int FG_Color_btnG;
    int FG_Color_btnB;
    Color FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);   
    
    int numSCR;
    int numSCG;
    int numSCB;
    Color mySelColor =  new Color(numSCR, numSCG, numSCB); 
    Color selectedColor;
    
    int myYellow_NumR=255, myYellow_NumG=225, myYellow_NumB=100;
    Color mySelected_Color =  new Color(myYellow_NumR, myYellow_NumG, myYellow_NumB);        
    
    String setMyLang="Greek";
    String setMyLangChars="gr" ;
    String pathMyLang="./languages/Greek/filename of theme_gr.lang";
    String myForm="/filename of theme_";
    
    public Saving_Theme() {
        initComponents();
        JFrame.setDefaultLookAndFeelDecorated(true); //for Title and Icon for Linux
        
        Image small_logo = new ImageIcon(this.getClass().getResource("/PolytLexplus_logo_256x256.png")).getImage();
        this.setIconImage(small_logo);
         setDefaultCloseOperation(Info.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_FilenameTheme_ = new javax.swing.JPanel();
        jTextField_Filename_ = new javax.swing.JTextField();
        jButton_OK_ = new javax.swing.JButton();
        jLabel_FilenameTheme_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ἀποθήκευση θέματος");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_FilenameTheme_.setBackground(new java.awt.Color(242, 242, 242));
        jPanel_FilenameTheme_.setPreferredSize(new java.awt.Dimension(430, 200));

        jTextField_Filename_.setBackground(new java.awt.Color(242, 242, 242));
        jTextField_Filename_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_Filename_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Filename_KeyReleased(evt);
            }
        });

        jButton_OK_.setBackground(new java.awt.Color(242, 242, 242));
        jButton_OK_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_OK_.setText("Ἐντάξει");
        jButton_OK_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OK_ActionPerformed(evt);
            }
        });

        jLabel_FilenameTheme_.setBackground(new java.awt.Color(242, 242, 242));
        jLabel_FilenameTheme_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_FilenameTheme_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FilenameTheme_.setText("Παρακαλῶ δῶστε τὸ ὄνομα τοῦ θέματος.");

        javax.swing.GroupLayout jPanel_FilenameTheme_Layout = new javax.swing.GroupLayout(jPanel_FilenameTheme_);
        jPanel_FilenameTheme_.setLayout(jPanel_FilenameTheme_Layout);
        jPanel_FilenameTheme_Layout.setHorizontalGroup(
            jPanel_FilenameTheme_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FilenameTheme_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_FilenameTheme_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_OK_, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Filename_, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_FilenameTheme_, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_FilenameTheme_Layout.setVerticalGroup(
            jPanel_FilenameTheme_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FilenameTheme_Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel_FilenameTheme_, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextField_Filename_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_OK_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_FilenameTheme_, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_FilenameTheme_, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OK_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OK_ActionPerformed
        
       if (myFilename=="") {
         Saving_Theme.this.dispose();   
        }    
       
       else {
           
      try {
      File saveTheme = new File(pathThemes + myFilename + ".thm");
      if (saveTheme.createNewFile()) {
        //System.out.println("Τὸ ἀρχεῖο δημιουργήθηκε: " + saveTheme.getName() + "\n");
        
        Saved_Theme JSavingTheme = new Saved_Theme();
        JSavingTheme.show();
        
        Saving_Theme.this.dispose();
       
            FileWriter fwTheme_ = new FileWriter("./themes/" + myFilename + ".thm");    
            fwTheme_.write(numR + "\n");
            fwTheme_.write(numG + "\n");
            fwTheme_.write(numB + "\n"); 
    
            fwTheme_.write(BG_Color_btnR + "\n");
            fwTheme_.write(BG_Color_btnG + "\n");
            fwTheme_.write(BG_Color_btnB + "\n");
            fwTheme_.write(BG_Color_listR + "\n");
            fwTheme_.write(BG_Color_listG + "\n");
            fwTheme_.write(BG_Color_listB + "\n");
    
            fwTheme_.write(FG_Color_btnR + "\n");
            fwTheme_.write(FG_Color_btnG + "\n");
            fwTheme_.write(FG_Color_btnB + "\n");
    
            fwTheme_.close();    
            
         
            }
          
        else {
         
        Saving_Theme_Error JSavingThemeError = new Saving_Theme_Error();
        JSavingThemeError.show(); 
        
        //System.out.println("Τὸ θέμα ὑπάρχει!");
        }
        }
     
      catch (IOException e) {
      //System.out.println("An error occurred.");
            }
       }  
       
    }//GEN-LAST:event_jButton_OK_ActionPerformed

    private void jTextField_Filename_KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Filename_KeyReleased
              
        myFilename=jTextField_Filename_.getText();
        
    }//GEN-LAST:event_jTextField_Filename_KeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        myFilename="";
        
        File fileBG = new File("./settings/colorbg.set");
        File fileBG_btn = new File("./settings/colorbtn.set");
        File fileFG_btn = new File("./settings/colorlttr.set");
        File fileMyLang = new File ("./settings/mylang.set");
        File fileMySelColor = new File("./settings/myselcolor.set");            
        
        try {
            
            Scanner sML = new Scanner(fileMyLang);
            setMyLang=(sML.nextLine());
            setMyLangChars=(sML.nextLine());
            pathMyLang="./languages/" + setMyLang + myForm + setMyLangChars +".lang";    
            //System.out.println("Γλώσσα: " + setMyLang + " [" + setMyLangChars + "] " + "\n");
            File fileSetMyLang= new File (pathMyLang);
            
            //System.out.println("\n");
            Scanner sBG = new Scanner( fileBG);
            //System.out.println("Χρώμα φόντου");
            numR=(sBG.nextInt());
            //System.out.println(numR);
            numG=(sBG.nextInt());
            //System.out.println(numG);
            numB=(sBG.nextInt());
            //System.out.println(numB);
            //System.out.println("\n");
            mycolor =new Color(numR, numG, numB);
            jPanel_FilenameTheme_.setBackground(mycolor);
            
            Scanner sBG_btn = new Scanner(fileBG_btn);
            //System.out.println("Χρώμα κουμπιών");
            BG_Color_btnR=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnR);
            BG_Color_btnG=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnG);
            BG_Color_btnB=(sBG_btn.nextInt());
            //System.out.println(BG_Color_btnB);
            //System.out.println("Χρώμα Λίστας/Πεδίου");
            BG_Color_listR=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listR);
            BG_Color_listG=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listG);
            BG_Color_listB=(sBG_btn.nextInt());
            //System.out.println(BG_Color_listB);
            //System.out.println("");
            //System.out.println("\n");
            BG_Color_btn =new Color(BG_Color_btnR, BG_Color_btnG, BG_Color_btnB);
            BG_Color_list=new Color(BG_Color_listR, BG_Color_listG, BG_Color_listB);
            
            Scanner sFG_btn = new Scanner(fileFG_btn);
            //System.out.println("Χρώμα γραμμάτων");
            FG_Color_btnR=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnR);
            FG_Color_btnG=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnG);
            FG_Color_btnB=(sFG_btn.nextInt());
            //System.out.println(FG_Color_btnB);
            //System.out.println("\n");
            FG_Color_btn = new Color (FG_Color_btnR, FG_Color_btnG, FG_Color_btnB);   
            
            jLabel_FilenameTheme_.setForeground(FG_Color_btn);
            jTextField_Filename_.setBackground(BG_Color_list);
            jTextField_Filename_.setForeground(FG_Color_btn);
            jButton_OK_.setBackground(BG_Color_btn);
            jButton_OK_.setForeground(FG_Color_btn);
            
            Scanner sMSC = new Scanner( fileMySelColor);
            //System.out.println("Ἐπιλεγμένο χρῶμα");
            numSCR=(sMSC.nextInt());
            //System.out.println(numSCR);
            numSCG=(sMSC.nextInt());
            //System.out.println(numSCG);
            numSCB=(sMSC.nextInt());
            //System.out.println(numSCB);
            //System.out.println("\n");
            mySelColor =new Color(numSCR, numSCG, numSCB);
            selectedColor=mySelColor;
            mySelected_Color=mySelColor;  
            jTextField_Filename_.setSelectionColor(selectedColor);            
            
            Scanner spathML = new Scanner(fileSetMyLang);
            
            setMyLang=(spathML.nextLine());
            this.setTitle(setMyLang);
                       
            setMyLang=(spathML.nextLine());
            jLabel_FilenameTheme_.setText(setMyLang);
                        
            setMyLang=(spathML.nextLine());
            jButton_OK_.setText(setMyLang);
                       
        }
        
        catch (FileNotFoundException ex) {
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saving_Theme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saving_Theme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saving_Theme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saving_Theme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saving_Theme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_OK_;
    private javax.swing.JLabel jLabel_FilenameTheme_;
    private javax.swing.JPanel jPanel_FilenameTheme_;
    private javax.swing.JTextField jTextField_Filename_;
    // End of variables declaration//GEN-END:variables
}
